language: python
python:
    - "3.5"
before_install:
    - sudo apt-get install torque-server torque-client torque-mom torque-pam
    - sudo ./setup_torque.sh
install:
    #- pip install payu  # Use this when pip is up to date
    - git clone https://github.com/marshallward/payu.git
    - cd payu
    - python setup.py install
    - cd ..
#before_script:
#    - cd test
#    - pip install -r requirements_test.txt
script:
    - echo "sleep 10" | qsub
    - payu
#after_success:
#    - coverage report -m
#    - coveralls
#sudo: False
